#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'
require 'rbbt/workflow'

Workflow.require_workflow "Study"

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap studies from a directory

$ rbbt workflow cmd Study [<directory>] [<study>,<study>,...]

If no directory is used, the default is used #{Sample.study_repo}

--cpus CPUs to use concurrently
-h--help Print this help
EOF
rbbt_usage and exit 0 if options[:help]

Sample.study_repo = Path.setup(ARGV.shift.dup) if ARGV.any? 

if ARGV.any?
  studies = Study.setup(ARGV.shift.split(","))
else
  studies = Sample.all_studies
end

$cpus ||= options[:cpus] || 3

Log.warn "STUDY BOOTSTRAP - 1"
Misc.bootstrap studies, [$cpus, studies.length].min, :respawn => :always do |study|
  Study.setup(study)

  job = study.sample_genes(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  study.knowledge_base.registry.keys.each do |database|
    study.knowledge_base.get_index(database).reverse
  end
  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end

Log.warn "STUDY BOOTSTRAP - 2"
Misc.bootstrap studies, [$cpus, studies.length].min, :respawn => :always do |study|
  Study.setup(study)
  job = study.firestar(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  job = study.kinmut(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end


Log.warn "STUDY BOOTSTRAP - 3"
Misc.bootstrap studies, 2, :respawn => :always do |study|

  Misc.bootstrap Enrichment::DATABASES, 2, :respawn => :always do |database|
    Study.setup(study)
    next if database == 'interpro'
    job = study.recurrent_gene_enrichment(:job, :database => database)
    if not job.done?
      job.run(true)
      Step.wait_for_jobs job
    end

    #study.mutation_enrichment(true, :database => database)
  end
  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end


Log.warn "STUDY BOOTSTRAP - 4"
Misc.bootstrap studies, 3, :respawn => :always do |study|
  Study.setup(study)
  job = study.firestar_neighbours(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end

Log.warn "STUDY BOOTSTRAP - 5"
Misc.bootstrap studies, 3, :respawn => :always do |study|
  Study.setup(study)
  job = study.mi_annotations(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  job = study.genomic_mutation_annotations(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end

Log.warn "STUDY BOOTSTRAP - 6"
Misc.bootstrap studies, 2, :respawn => :always do |study|
  Study.setup(study)
  job = study.binomial_significance(:job)
  if not job.done?
    job.run(true)
    Step.wait_for_jobs job
  end

  Misc.bootstrap Enrichment::DATABASES, 2, :respawn => :always do |database|
    job = study.significant_gene_enrichment(:job, :database => database)
    if not job.done?
      job.run(true)
      Step.wait_for_jobs job
    end

  end
  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end

Log.warn "STUDY BOOTSTRAP - 7"
Misc.bootstrap studies, 2, :respawn => :always do |study|

  Misc.bootstrap Enrichment::DATABASES, 2, :respawn => :always do |database|
    Study.setup(study)
    next if database == 'interpro'
    job = study.sample_enrichment(:job, :database => database)
    if not job.done?
      job.run(true)
      Step.wait_for_jobs job
    end

    #study.mutation_enrichment(true, :database => database)
  end
  Log.warn "STUDY BOOTSTRAP - " + study
  nil
end
