#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'
require 'rbbt/workflow'

Workflow.require_workflow "Study"

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap studies from a directory

$ rbbt workflow cmd Study [<directory>] [<study>,<study>,...]

If no directory is used, the default is used #{Sample.study_repo}

--cpus CPUs to use concurrently
-h--help Print this help
EOF
rbbt_usage and exit 0 if options[:help]

Sample.study_repo = Path.setup(ARGV.shift.dup) if ARGV.any? 

if ARGV.any?
  studies = Study.setup(ARGV.shift.split(","))
else
  studies = Sample.all_studies
end

$cpus ||= options[:cpus] || 3

Misc.bootstrap studies, $cpus, :respawn => :always do |study|
  Study.setup(study)

  #Misc.bootstrap study.genotyped_samples, $cpus.to_i / 2 do |sample|
  #  sample.genomic_mutation_annotations
  #  sample.mutation_mi_annotations
  #  sample.mutation_details
  #end

  study.sample_genes

  study.knowledge_base.registry.keys.each do |database|
    study.knowledge_base.get_index(database).reverse
  end
  nil
end

Misc.bootstrap studies, $cpus, :respawn => :always do |study|
  Study.setup(study)
  study.firestar
  study.kinmut
  nil
end


Misc.bootstrap studies, $cpus/2, :respawn => :always do |study|

  Misc.bootstrap Enrichment::DATABASES, 2, :respawn => :always do |database|
    Study.setup(study)
    next if database == 'interpro'
    study.recurrent_gene_enrichment(true, :database => database)
    #study.mutation_enrichment(true, :database => database)
  end
  nil
end


Misc.bootstrap studies, 3, :respawn => :always do |study|
  Study.setup(study)
  study.firestar_neighbours
  nil
end

Misc.bootstrap studies, 3, :respawn => :always do |study|
  Study.setup(study)
  study.mi_annotations
  study.genomic_mutation_annotations
  nil
end

Misc.bootstrap studies, $cpus, :respawn => :always do |study|
  Study.setup(study)
  study.binomial_significance
  Misc.bootstrap Enrichment::DATABASES, 2, :respawn => :always do |database|
    study.significant_gene_enrichment(true, :database => database)
  end
  nil
end

Misc.bootstrap studies, $cpus/2, :respawn => :always do |study|

  Misc.bootstrap Enrichment::DATABASES, 2, :respawn => :always do |database|
    Study.setup(study)
    next if database == 'interpro'
    study.sample_enrichment(true, :database => database)
    #study.mutation_enrichment(true, :database => database)
  end
  nil
end
