#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Turn a MAF file into a project directory

$ #{$0} <filename.maf> <directory>

-h--help Print this help
-o--organism* Organism code
-w--watson Mutations given in the watson or forward strand
-ex--exome Exome sequencing, as opposed to Whole Genome
-u--users* Users allowed for these studies
-c--chromosome_field* Chromosome field in MAF
-s--start_field* Start field in MAF
-e--end_field* End field in MAF
-r--reference_field* Reference allele field in MAF
-a--alternate_field* Alternative allele field in MAF
-a2--alternate_field2* Alternative allele field in MAF 2
-d--donor_field* Donor fieldin MAF
-sf--study_field* Study fieldin MAF
-si--sample_ids* Sample identifier map
-exp--expression* Expression matrix file
-et--expression_type* Expression type (options are log2, counts, fkpm, rpkm; defaults to log2 values)
-ei--expression_id* Sample id field for expression values
-ein--expression_id_normal* Sample id field for normal expression values
-bl--blacklist* Blacklisted donor ids
-mr--mappable_regions* Mappable region file to add to project
EOF

if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.usage
  end
  exit 0
end

filename, $directory = ARGV

raise "No filename specified" if filename.nil?
raise "File not found: #{ filename }" unless Open.exists? filename

c_field = options[:chromosome_field] || "Chromosome"
s_field = options[:start_field] || "Start_position"
e_field = options[:end_field] || "End_position"
r_field = options[:reference_field] || "Reference_Allele"
a_field = options[:alternate_field] || "Alternate_Allele"
a2_field = options[:alternate_field2]
d_field = options[:donor_field] || "Donor_ID"
sf_field = options[:study_field] || "Project_Code"
blacklist_file = options[:blacklist]


blacklist_file ||= 'blacklist-donors'
if File.exists? blacklist_file
  blacklist = Set.new(Open.read(blacklist_file).split("\n"))
else
  blacklist = Set.new
end

organism = options[:organism] || Organism.default_code("Hsa")
watson = options[:watson]
watson = true if watson.nil?
exome = options[:exome]
exome = true if exome.nil?
users = (options[:users] || 'public' ).split(",").collect{|u| u.strip }


filename = Path.setup(filename.dup)

all_fields = Open.gzip?(filename) ? 
    CMD.cmd("zcat #{filename} | head -n 1 ").read.sub(/^#/,'').split("\t") : 
    CMD.cmd("head -n 1 #{filename}").read.sub(/^#/,'').split("\t")  

c_pos  = Misc.field_position all_fields, c_field
s_pos  = Misc.field_position all_fields, s_field
e_pos  = Misc.field_position all_fields, e_field
r_pos  = Misc.field_position all_fields, r_field
a_pos  = Misc.field_position all_fields, a_field
if a2_field
  a2_pos  = Misc.field_position all_fields, a2_field
else
  a2_pos  = a_pos
end
d_pos  = Misc.field_position all_fields, d_field
sf_pos = Misc.field_position all_fields, sf_field

$directory = './project' unless $directory

$sample_streams = {}
def sample_stream(sample, study)
  mutation_file = File.join($directory, study, 'genotypes', sample)
  FileUtils.mkdir_p File.dirname(mutation_file) unless File.exists? File.dirname(mutation_file)
  Open.open(mutation_file, :mode => 'a')
end

sample_study = {}
study_samples = {}
studies = Set.new
all_samples = Set.new
TSV.traverse filename, :bar => true, :type => :array do |line|
  begin
    line = Misc.fixutf8 line
  next if line =~ /Chromosome/
  chr, start, eend, ref, _mut1, _mut2, sample, study = line.split("\t").values_at c_pos, s_pos, e_pos, r_pos, a_pos, a2_pos, d_pos, sf_pos
  next if blacklist.include? sample

  start = start.to_i
  eend = eend.to_i

  _muts = ([_mut1, _mut2].compact.uniq - [ref])
  _mut  = _muts.first

  pos, muts = Misc.correct_vcf_mutation start, ref, _mut
  mutations = muts.collect{|m| [chr, pos, m] * ":"}

  sample_study[sample] ||= study
  study_samples[study] ||= Set.new
  study_samples[study].add sample
  studies.add study
  all_samples.add sample

  stream = sample_stream(sample, study)

  stream.puts mutations * "\n"
  stream.close
  rescue
    raise $!
  end
end

# ADD METADATA
metadata_all = {:organism => organism, :watson => watson, :exome => exome, :users => users}
metadata_all[:expression_type] = options[:expression_type] if options[:expression_type]
map_file = options[:mappable_regions]
studies.each do |study|
  metadata = metadata_all.dup
  metadata[:condition] = study
  Open.write(File.join($directory, study, 'metadata.yaml'), metadata.to_yaml)
  FileUtils.cp map_file, File.join($directory, study, 'mappable_regions') if map_file
end

# ADD EXPRESSION
if options[:expression]
  donor_field, count = TSV.guess_id options[:sample_ids], all_samples.to_a, :header_hash => true, :persist_update => true
  raise "Sample field not found" if donor_field.nil?
  Log.info "Using donor_field: " << donor_field
  sample_id_tsv = TSV.open options[:sample_ids], :type => :list, :header_hash => true, :unnamed => true, :key_field => donor_field

  matrix = TSV.open(options[:expression], :header_hash => true, :type => :list, :namespace => organism, :unnamed => true, :fix => Proc.new{|l| l.sub(/(ENSG\d+)\.\d+/,'\1')})
  #matrix.key_field = "Ensembl Gene ID"
  found = Organism.guess_id(organism, matrix.keys)
  matrix.key_field = found.first if found
  matrix_fields = matrix.fields

  expression_index = TSV.open(options[:sample_ids], :key_field => donor_field, :fields => [options[:expression_id]], :type => :single) if options[:expression_id]
  expression_index_normal = TSV.open(options[:sample_ids], :key_field => donor_field, :fields => [options[:expression_id_normal]], :type => :single) if options[:expression_id_normal]
  TSV.traverse studies.to_a, :bar => "Traversing studies for gene expression" do |study|
    samples = study_samples[study]
    if options[:expression_id]
      sample_ids = expression_index.chunked_values_at samples.to_a
    else
      sample_ids = samples.to_a
    end

    sample_ids.reject!{|id| id.nil? or id == ""}

    if sample_ids.any?
      sample_equivalence = {}
      samples.zip(sample_ids).each do |sample, eid|
        next if eid.nil? or eid.empty?
        matching_eids = matrix_fields.select{|f| eid =~ /(?:\W|^)#{f}(?:\W|$)/} 
        Log.warn "NO matching expression column for #{ eid }" and next if matching_eids.empty?
        raise "Several matching expression columns for #{ eid }: " << matching_eids*", " if matching_eids.length > 1
        sample_equivalence[matching_eids.first] = sample
      end

      study_matrix = matrix.slice(sample_equivalence.keys & matrix_fields)
      study_matrix.fields = sample_equivalence.chunked_values_at study_matrix.fields
      Open.write(File.join($directory, study, 'matrices', 'gene_expression', 'data'), study_matrix.to_s)
    end

    if options[:expression_id_normal]
      sample_ids = expression_index_normal.chunked_values_at samples.to_a

      sample_ids.reject!{|id| id.nil? or id == ""}

      if sample_ids.any?
        sample_equivalence = {}
        samples.zip(sample_ids).each do |sample, eid|
          next if eid.nil? or eid.empty?
          matching_eids = matrix_fields.select{|f| eid =~ /(?:\W|^)#{f}(?:\W|$)/} 
          Log.warn "NO matching expression column for #{ eid }" and next if matching_eids.empty?
          raise "Several matching expression columns for #{ eid }: " << matching_eids*", " if matching_eids.length > 1
          sample_equivalence[matching_eids.first] = sample
        end

        study_matrix = matrix.slice(sample_equivalence.keys & matrix.fields)
        study_matrix.fields = sample_equivalence.chunked_values_at study_matrix.fields
        Open.write(File.join($directory, study, 'matrices', 'gene_expression', 'data_normal'), study_matrix.to_s)
      end
    end
  end
end

